baseURL = "http://example.org/"
languageCode = "en-us"
title = "Portfolio | Astha Nayak"
theme = "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production 
    title: Portfolio | Astha Nayak
    description: "ExampleSite description"
    keywords: [Developer, Portfolio, PaperMod, Hugo]
    author: Astha Nayak
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: dark
    disableThemeToggle: false
