name: portfolio
description: Astha Nayak's Portfolio Website

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  google_fonts: ^2.1.0
  responsive_builder: ^0.4.1
  font_awesome_flutter: ^9.1.0 
  url_launcher: ^6.0.9 
  flutter_feather_icons: ^2.0.0+1
  flutter_web_plugins:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/docs/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Circe
      fonts:
        - asset: assets/fonts/circe/Circe-Thin.ttf
          weight: 200
        - asset: assets/fonts/circe/Circe-Light.ttf
          weight: 300
        - asset: assets/fonts/circe/Circe-Bold.ttf
          weight: 600
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proxima_nova/ProximaNova-Thin.otf
          weight: 200
        - asset: assets/fonts/proxima_nova/ProximaNova-Regular.otf
          weight: 400
        - asset: assets/fonts/proxima_nova/ProximaNova-Bold.otf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
